### ISSUE TITLE
Question about withLatestFrom behavior

### ISSUE THREAD

**Issue by cuzv** [CombineCommunity/CombineExt#107]
After https://github.com/CombineCommunity/CombineExt/pull/105 were merged.
The code working before from my project not anymore.

Here is a gist:

```Swift
final class ViewModel: ObservableObject {
    @Published var singal1 = true
    @Published var singal2 = true
}

func testWithPublished() {
    var results = [Bool]()
    
    subscription = model.$singal1.withLatestFrom(model.$singal2) {
        $0 && $1
    }
    .sink(receiveValue: { value in
        results.append(value)
    })

    model.singal1 = false
    
    XCTAssertEqual(results, [true, false])
}
```

As my expect, results should be `[true, false]`, instead of just `[true]`. Am I misunderstand the behavior of `withLatestFrom`?

**Comment by hebdavepaul0** [comment]
I'm also getting failing tests after updating to CombineExt 1.5.0 for the Swift release bug workaround.

Are the changes in withLatestFrom behavior documented anywhere?

**Comment by freak4pc** [comment]
Hey @cuzv @hebdavepaul0, that's interesting. Would be good to make a test to fail on our side. 
We might've been to quick to accept the alternative implementation. 

@jasdev - do you have time to look into why this isn't behaving as expected? Otherwise let me know and I'll cut a 1.5.1 with the previous implementation.

Thanks!

**Comment by jasdev** [comment]
My hunch is the new approach doesn’t handle value-typed `Publisher` conformances ([`Published.Publisher`](https://developer.apple.com/documentation/combine/published/publisher) is a struct), since the composed alternative relies on reference capture.

I unfortunately don’t have much time these days for Ext work, so let’s revert for now. 🙏🏽 Thanks for filing this @hebdavepaul0!

**Comment by freak4pc** [comment]
1.5.1 has been released with the previous implementation. Sorry for the hiccup!

**Comment by hebdavepaul0** [comment]
thanks for the quick action @freak4pc!
