### ISSUE TITLE
Rename Relay.accept(_ value:)

### ISSUE THREAD

**Issue by dsk1306** [CombineCommunity/CombineExt#35]
Do you think it would be better to rename it to `send(_ input:)` to follow `PassthroughSubject.send(_ input:)` and `CurrentValueSubject.send(_ input:)` naming pattern?

**Comment by freak4pc** [comment]
Relay isn't really a Combine concept, it comes from RxJava originally (RxRelay specifically by Jake Wharton), and they do have a different naming (onNext/accept) to differentiate that a relay accepts messages (which it only "relays"). 

I think it's nice keeping the naming familiar so Relays are still obvious to people coming from other Rx implementations and also since the naming does make sense IMO

**Comment by freak4pc** [comment]
Any other thoughts @dsk1306 ?

**Comment by dsk1306** [comment]
Not really. I thought it would be nice to follow the same naming pattern but I agree with your point.
